import os
import json

# DataHub Copilot - Metadata-Aware AI Agent
class DataHubCopilot:
    def __init__(self, datahub_url="http://localhost:8080"):
        self.datahub_url = datahub_url
        print(f" Connected to DataHub Context Platform at {self.datahub_url}")

    def fetch_schema_metadata(self, dataset_name):
        """Simulates fetching real-time metadata context from DataHub MCP Server."""
        mock_datahub_catalog = {
            "zava_products": {
                "columns": ["product_id", "product_name", "category", "revenue", "status"],
                "lineage": "upstream: raw_sales_db -> downstream: zava_analytics"
            }
        }
        return mock_datahub_catalog.get(dataset_name, None)

    def generate_sql(self, user_prompt, dataset_name):
        """Generates zero-hallucination SQL query using DataHub metadata context."""
        metadata = self.fetch_schema_metadata(dataset_name)
        if not metadata:
            return " Error: Dataset schema not found in DataHub catalog."
        
        cols = ", ".join(metadata["columns"])
        print(f" [DataHub Context Loaded] Columns: {cols}")
        
        sql_query = f"""
-- Generated by DataHub Copilot (Context-Aware)
-- Lineage: {metadata['lineage']}
SELECT product_name, category, SUM(revenue) AS total_revenue
FROM {dataset_name}
WHERE status = 'Active'
GROUP BY product_name, category
ORDER BY total_revenue DESC;
        """
        return sql_query

if __name__ == "__main__":
    copilot = DataHubCopilot()
    prompt = "Find top revenue generating products in active status"
    print(f"\nUser Query: '{prompt}'\n")
    result = copilot.generate_sql(prompt, "zava_products")
    print(result)

